name = "affiliate-do"
main = "do-worker.js"
compatibility_date = "2024-01-01"

[[durable_objects.bindings]]
name = "AFFILIATE_DO"
class_name = "AffiliateCounter"

[[migrations]]
tag = "v1"
new_classes = [ "AffiliateCounter" ]
